# Setup
title:               Kaden Uhlig's thoughts
tagline:             'A place for me to gather my thoughts, experiences and ideas'
description:         'Kaden Uhlig&quote;s personal blog. A place for me to gather my thoughts, experiences and ideas, and hopefully share them with others. Let me know if you enjoy it!'
url:                 https://numeri.github.io
baseurl:             'https://numeri.github.io/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Kaden Uhlig
  url:               https://github.com/Numeri
  email:             kaden.uhlig+blog@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
