# Setup
title:               Kaden Uhlig
tagline:             'A place to gather my thoughts, experiences and ideas'
description:         'Kaden Uhlig&rsquo;s personal blog. A place for me to gather my thoughts, experiences and ideas &ndash; and hopefully share them with others.'
url:                 https://numeri.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Kaden Uhlig
  url:               https://github.com/Numeri
  email:             kaden.uhlig+blog@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
